services:
  postgres:
    image: postgres:latest
    container_name: lab-2-tools-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5431:5432"
    restart: unless-stopped
    networks:
      - configuration-service-network
  
  configuration-service:
    image: ghcr.io/is-csms-y27/lab-2-tools:master
    platform: linux/amd64
    container_name: configuration-service
    networks:
      - configuration-service-network
    depends_on:
      - postgres
    ports:
      - '8081:8081'
    environment:
      Persistence__Postgres__Host: postgres

  postgres-Order-DB:
    image: postgres:latest
    container_name: lab-3-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orderDB
    ports:
      - "5433:5432"
    restart: unless-stopped
    command: ["postgres", "-c", "max_prepared_transactions=10"]

networks:
  configuration-service-network:
    driver: bridge